name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  env:
    # AWS secrets
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # For checking the format for terraform code
    - name: Terraform fmt
      id: fmt
      run: |
        terraform fmt

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      env:
        TF_CLOUD_ORGANIZATION: "Org-Development"
        TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
        TF_WORKSPACE: "terraform-github-actions"
      run: |
        terraform init

    - name: Terraform plan
      id: plan
      env:
        TF_CLOUD_ORGANIZATION: "Org-Development"
        TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
        TF_WORKSPACE: "terraform-github-actions"
      run: |
        terraform plan




